//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pixeria.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kommentar
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public int UserId { get; set; }
        public int DokumentId { get; set; }
    
        public virtual Dokument Dokument { get; set; }
        public virtual User User { get; set; }
    }
}
